// import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function PrivacyLayout({ children }) {
  return (
    <div style={{margin: '40px'}}>
      <div>Privacy Terms</div>
      <div>{children}</div>
    </div>
  )
}
